<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('products')->insert([
            [
                'name' => 'Product 1',
                'author' => 'Author 1',
                'publishing_company' => 'Company 1',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2020,
                'packaging_size' => '20x15x3 cm',
                'weight' => 500,
                'quantity' => 10,
                'description_long' => 'Description for product 1',
                'delete_flag' => 1,
                'category_id' => 1,
                'provider_id'=> 1,
            ],
            [
                'name' => 'Product 2',
                'author' => 'Author 2',
                'publishing_company' => 'Company 2',
                'cover_form' => 'Paperback',
                'publishing_year' => 2019,
                'packaging_size' => '21x14x2 cm',
                'weight' => 300,
                'quantity' => 15,
                'description_long' => 'Description for product 2',
                'delete_flag' => 1,
                'category_id' => 2,
                'provider_id'=> 2,
            ],
            // Repeat similar entries for Products 3 to 20
            [
                'name' => 'Product 3',
                'author' => 'Author 3',
                'publishing_company' => 'Company 3',
                'cover_form' => 'Paperback',
                'publishing_year' => 2018,
                'packaging_size' => '20x13x2 cm',
                'weight' => 400,
                'quantity' => 20,
                'description_long' => 'Description for product 3',
                'delete_flag' => 1,
                'category_id' => 3,
                'provider_id'=> 3,
            ],
            [
                'name' => 'Product 4',
                'author' => 'Author 4',
                'publishing_company' => 'Company 4',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2021,
                'packaging_size' => '22x16x4 cm',
                'weight' => 600,
                'quantity' => 5,
                'description_long' => 'Description for product 4',
                'delete_flag' => 1,
                'category_id' => 4,
                'provider_id'=> 4,
            ],
            [
                'name' => 'Product 5',
                'author' => 'Author 5',
                'publishing_company' => 'Company 5',
                'cover_form' => 'Paperback',
                'publishing_year' => 2017,
                'packaging_size' => '19x14x1 cm',
                'weight' => 350,
                'quantity' => 25,
                'description_long' => 'Description for product 5',
                'delete_flag' => 1,
                'category_id' => 5,
                'provider_id'=> 5,
            ],
            [
                'name' => 'Product 6',
                'author' => 'Author 6',
                'publishing_company' => 'Company 6',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2022,
                'packaging_size' => '23x15x3 cm',
                'weight' => 450,
                'quantity' => 8,
                'description_long' => 'Description for product 6',
                'delete_flag' => 1,
                'category_id' => 6,
                'provider_id'=> 6,
            ],
            [
                'name' => 'Product 7',
                'author' => 'Author 7',
                'publishing_company' => 'Company 7',
                'cover_form' => 'Paperback',
                'publishing_year' => 2016,
                'packaging_size' => '21x14x2 cm',
                'weight' => 320,
                'quantity' => 30,
                'description_long' => 'Description for product 7',
                'delete_flag' => 1,
                'category_id' => 1,
                'provider_id'=> 7,
            ],
            [
                'name' => 'Product 8',
                'author' => 'Author 8',
                'publishing_company' => 'Company 8',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2020,
                'packaging_size' => '20x13x3 cm',
                'weight' => 500,
                'quantity' => 10,
                'description_long' => 'Description for product 8',
                'delete_flag' => 1,
                'category_id' => 2,
                'provider_id'=> 8,
            ],
            [
                'name' => 'Product 9',
                'author' => 'Author 9',
                'publishing_company' => 'Company 9',
                'cover_form' => 'Paperback',
                'publishing_year' => 2015,
                'packaging_size' => '21x14x2 cm',
                'weight' => 280,
                'quantity' => 20,
                'description_long' => 'Description for product 9',
                'delete_flag' => 1,
                'category_id' => 3,
                'provider_id'=> 9,
            ],
            [
                'name' => 'Product 10',
                'author' => 'Author 10',
                'publishing_company' => 'Company 10',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2021,
                'packaging_size' => '22x15x4 cm',
                'weight' => 550,
                'quantity' => 7,
                'description_long' => 'Description for product 10',
                'delete_flag' => 1,
                'category_id' => 4,
                'provider_id'=> 10,
            ],
            [
                'name' => 'Product 11',
                'author' => 'Author 11',
                'publishing_company' => 'Company 11',
                'cover_form' => 'Paperback',
                'publishing_year' => 2019,
                'packaging_size' => '21x14x1 cm',
                'weight' => 300,
                'quantity' => 25,
                'description_long' => 'Description for product 11',
                'delete_flag' => 1,
                'category_id' => 5,
                'provider_id'=> 1,
            ],
            [
                'name' => 'Product 12',
                'author' => 'Author 12',
                'publishing_company' => 'Company 12',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2018,
                'packaging_size' => '20x15x3 cm',
                'weight' => 480,
                'quantity' => 15,
                'description_long' => 'Description for product 12',
                'delete_flag' => 1,
                'category_id' => 6,
                'provider_id'=> 2,
            ],
            [
                'name' => 'Product 13',
                'author' => 'Author 13',
                'publishing_company' => 'Company 13',
                'cover_form' => 'Paperback',
                'publishing_year' => 2017,
                'packaging_size' => '21x13x2 cm',
                'weight' => 340,
                'quantity' => 18,
                'description_long' => 'Description for product 13',
                'delete_flag' => 1,
                'category_id' => 1,
                'provider_id'=> 3,
            ],
            [
                'name' => 'Product 14',
                'author' => 'Author 14',
                'publishing_company' => 'Company 14',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2022,
                'packaging_size' => '23x14x3 cm',
                'weight' => 490,
                'quantity' => 12,
                'description_long' => 'Description for product 14',
                'delete_flag' => 1,
                'category_id' => 2,
                'provider_id'=> 4,
            ],
            [
                'name' => 'Product 15',
                'author' => 'Author 15',
                'publishing_company' => 'Company 15',
                'cover_form' => 'Paperback',
                'publishing_year' => 2016,
                'packaging_size' => '20x14x2 cm',
                'weight' => 310,
                'quantity' => 22,
                'description_long' => 'Description for product 15',
                'delete_flag' => 1,
                'category_id' => 3,
                'provider_id'=> 5,
            ],
            [
                'name' => 'Product 16',
                'author' => 'Author 16',
                'publishing_company' => 'Company 16',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2020,
                'packaging_size' => '22x15x3 cm',
                'weight' => 530,
                'quantity' => 9,
                'description_long' => 'Description for product 16',
                'delete_flag' => 1,
                'category_id' => 4,
                'provider_id'=> 6,
            ],
            [
                'name' => 'Product 17',
                'author' => 'Author 17',
                'publishing_company' => 'Company 17',
                'cover_form' => 'Paperback',
                'publishing_year' => 2015,
                'packaging_size' => '21x14x1 cm',
                'weight' => 290,
                'quantity' => 27,
                'description_long' => 'Description for product 17',
                'delete_flag' => 1,
                'category_id' => 5,
                'provider_id'=> 7,
            ],
            [
                'name' => 'Product 18',
                'author' => 'Author 18',
                'publishing_company' => 'Company 18',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2021,
                'packaging_size' => '20x13x4 cm',
                'weight' => 580,
                'quantity' => 6,
                'description_long' => 'Description for product 18',
                'delete_flag' => 1,
                'category_id' => 6,
                'provider_id'=> 8,
            ],
            [
                'name' => 'Product 19',
                'author' => 'Author 19',
                'publishing_company' => 'Company 19',
                'cover_form' => 'Paperback',
                'publishing_year' => 2019,
                'packaging_size' => '21x14x2 cm',
                'weight' => 350,
                'quantity' => 19,
                'description_long' => 'Description for product 19',
                'delete_flag' => 1,
                'category_id' => 1,
                'provider_id'=> 9,
            ],
            [
                'name' => 'Product 20',
                'author' => 'Author 20',
                'publishing_company' => 'Company 20',
                'cover_form' => 'Hardcover',
                'publishing_year' => 2018,
                'packaging_size' => '23x15x3 cm',
                'weight' => 450,
                'quantity' => 14,
                'description_long' => 'Description for product 20',
                'delete_flag' => 1,
                'category_id' => 2,
                'provider_id'=> 10,
            ],
        ]);
    }
}
